apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: econ-graph
  labels:
    app: loki
spec:
  type: ClusterIP
  ports:
  - port: 3100
    targetPort: 3100
  selector:
    app: loki
