apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: econ-graph
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki-service:3100/loki/api/v1/push
    scrape_configs:
    - job_name: econ-graph-logs
      static_configs:
      - targets:
        - localhost
        labels:
          job: econ-graph-logs
          app: econ-graph-backend
          namespace: econ-graph
          container: backend
          __path__: /var/log/pods/econ-graph_econ-graph-backend-7bf6cfdbbb-8bg9q_b4ee8f92-bc07-4252-b5aa-01a69cbc5ad4/backend/0.log
      - targets:
        - localhost
        labels:
          job: econ-graph-logs
          app: econ-graph-backend
          namespace: econ-graph
          container: backend
          __path__: /var/log/pods/econ-graph_econ-graph-backend-7bf6cfdbbb-qdxtp_a76eb053-ef91-4a66-9ee8-c7fd3a1e5275/backend/0.log
      pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+) (?P<stream>stdout|stderr) (?P<flags>\S+) (?P<content>.*)$'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          stream:
          flags:
      - output:
          source: content
