version: '3.8'

services:
  financial-data-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - DATA_DIR=/app/data
    volumes:
      - financial-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - financial-data-network

  # Optional: Add MinIO for future storage testing
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - financial-data-network
    profiles:
      - storage

volumes:
  financial-data:
    driver: local
  minio-data:
    driver: local

networks:
  financial-data-network:
    driver: bridge
