repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: migration-date-order-check
        name: Database Migration Date Order Check
        entry: bash -c 'cd backend && python3 scripts/check_migration_order.py'
        language: system
        files: ^backend/migrations/.*\.sql$
        pass_filenames: false
