#!/usr/bin/env python3
# Copyright (c) 2024 EconGraph. All rights reserved.
# Licensed under the Microsoft Reference Source License (MS-RSL).
# See LICENSE file for complete terms and conditions.
"""Builds crates/econ-graph-core/data/countries.csv, the shared country reference table.

Rows:
- every ISO 3166-1 country, from the iso-codes project's JSON (Debian/Ubuntu package
  `iso-codes`, /usr/share/iso-codes/json/iso_3166-1.json), keyed by ISO alpha-3;
- Kosovo (XK / XKX, user-assigned codes used by the World Bank, IMF and EU; no numeric code);
- the World Bank aggregates listed in AGGREGATES, keyed by their World Bank code, with no ISO
  codes and no name.

Columns: key, kind, iso2, iso3, iso_numeric, wb_code, sdmx_ref_area, name.

The script needs no network. `wb_code` is the ISO alpha-3 code (the World Bank uses alpha-3 for
its economies), except for the countries in NOT_WORLD_BANK. `sdmx_ref_area` is the ISO alpha-2
code (the CL_AREA convention of ECB, BIS and IMF).

Which aggregates we carry is our choice; what they are called is the World Bank's, so their rows
have no name. The World Bank crawl fetches the names from https://api.worldbank.org/v2/country
into the database (see econ-graph-crawler's sources/world_bank.rs), and a new database gets them
from the recorded seed migration.

`--check` builds the table and exits 1 if its rows differ from the file's, without writing (the
comment lines, which name the iso-codes version, are not compared). It is a manual check, not
run in CI.

Usage (from backend/):
    python3 scripts/build_countries_csv.py [--iso-json PATH] [--out PATH] [--check]
"""

import argparse
import csv
import io
import json
import subprocess
import sys
from pathlib import Path

DEFAULT_ISO_JSON = Path("/usr/share/iso-codes/json/iso_3166-1.json")
DEFAULT_OUT = Path(__file__).resolve().parent.parent / "crates/econ-graph-core/data/countries.csv"

COLUMNS = [
    "key", "kind", "iso2", "iso3", "iso_numeric", "wb_code",
    "sdmx_ref_area", "name",
]

# World Bank aggregates carried as rows (key = World Bank code): World, Euro area, European
# Union, and the income groups (high, upper middle, lower middle, low, middle, low & middle).
AGGREGATES = ["WLD", "EMU", "EUU", "HIC", "UMC", "LMC", "LIC", "MIC", "LMY"]

# Countries not in ISO 3166-1: (iso2, iso3, name).
EXTRA_COUNTRIES = [("XK", "XKX", "Kosovo")]

# Countries the World Bank does not publish, so they get no default wb_code.
NOT_WORLD_BANK = {"TWN"}


def country_rows(iso_json: Path) -> list[dict]:
    try:
        entries = json.loads(iso_json.read_text(encoding="utf-8"))["3166-1"]
    except FileNotFoundError:
        sys.exit(f"{iso_json} not found: install the iso-codes package or pass --iso-json")
    rows = [
        country_row(e["alpha_2"], e["alpha_3"], e["numeric"], e.get("common_name") or e["name"])
        for e in entries
    ]
    rows += [country_row(iso2, iso3, "", name) for iso2, iso3, name in EXTRA_COUNTRIES]
    return sorted(rows, key=lambda r: r["key"])


def country_row(iso2: str, iso3: str, numeric: str, name: str) -> dict:
    return {
        "key": iso3, "kind": "country", "iso2": iso2, "iso3": iso3,
        "iso_numeric": numeric, "wb_code": "" if iso3 in NOT_WORLD_BANK else iso3,
        "sdmx_ref_area": iso2, "name": name,
    }


def aggregate_rows() -> list[dict]:
    return [
        {**{c: "" for c in COLUMNS}, "key": code, "kind": "aggregate",
         "wb_code": code}
        for code in AGGREGATES
    ]


def split_file(text: str) -> tuple[list[str], list[str]]:
    """Returns the file's comment lines and its CSV lines."""
    lines = text.splitlines()
    return ([l for l in lines if l.startswith("#")], [l for l in lines if not l.startswith("#")])


def installed_iso_codes_version() -> str:
    try:
        return subprocess.run(["dpkg-query", "-W", "-f=${Version}", "iso-codes"],
                              capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "(version unknown)"


def render(rows: list[dict], iso_version: str) -> str:
    source = f"iso-codes {iso_version}"
    out = io.StringIO()
    out.write("# Country and aggregate reference table, read at runtime from $REFERENCE_DATA_DIR.\n")
    out.write(f"# Generated by backend/scripts/build_countries_csv.py from {source}; "
              "do not edit by hand.\n")
    w = csv.DictWriter(out, fieldnames=COLUMNS, lineterminator="\n")
    w.writeheader()
    w.writerows(rows)
    return out.getvalue()


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--iso-json", type=Path, default=DEFAULT_ISO_JSON)
    p.add_argument("--iso-version",
                   help="iso-codes version recorded in the file (default: the installed package's)")
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    p.add_argument("--check", action="store_true",
                   help="exit 1 if the file's rows differ from a fresh build; write nothing")
    args = p.parse_args()

    rows = country_rows(args.iso_json) + aggregate_rows()
    text = render(rows, args.iso_version or installed_iso_codes_version())
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if split_file(current)[1] != split_file(text)[1]:
            print(f"{args.out} is out of date; rerun {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {len(rows)} rows to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
