version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=econ_graph_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test-network

  # Backend service (pre-built)
  backend:
    build:
      context: ../../backend
      dockerfile: ci/docker/Dockerfile.test
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/econ_graph_test
      - RUST_LOG=info
    ports:
      - "9876:9876"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - test-network

  # Frontend service (pre-built)
  frontend:
    build:
      context: ../../frontend
      dockerfile: ci/docker/Dockerfile.test
    ports:
      - "18473:18473"
    depends_on:
      - backend
    networks:
      - test-network

  # Test runners (parallel execution)
  test-core:
    build:
      context: ../../
      dockerfile: ci/docker/Dockerfile.test-runner
    environment:
      - BACKEND_URL=http://backend:9876
      - FRONTEND_URL=http://frontend:18473
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/econ_graph_test
    command: ["npm", "run", "test:e2e:core"]
    volumes:
      - ./test-results/core:/app/test-results
    depends_on:
      - frontend
    networks:
      - test-network

  test-analysis:
    build:
      context: ../../
      dockerfile: ci/docker/Dockerfile.test-runner
    environment:
      - BACKEND_URL=http://backend:9876
      - FRONTEND_URL=http://frontend:18473
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/econ_graph_test
    command: ["npm", "run", "test:e2e:analysis"]
    volumes:
      - ./test-results/analysis:/app/test-results
    depends_on:
      - frontend
    networks:
      - test-network

  test-debug:
    build:
      context: ../../
      dockerfile: ci/docker/Dockerfile.test-runner
    environment:
      - BACKEND_URL=http://backend:9876
      - FRONTEND_URL=http://frontend:18473
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/econ_graph_test
    command: ["npm", "run", "test:e2e:debug"]
    volumes:
      - ./test-results/debug:/app/test-results
    depends_on:
      - frontend
    networks:
      - test-network

  test-comprehensive:
    build:
      context: ../../
      dockerfile: ci/docker/Dockerfile.test-runner
    environment:
      - BACKEND_URL=http://backend:9876
      - FRONTEND_URL=http://frontend:18473
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/econ_graph_test
    command: ["npm", "run", "test:e2e:comprehensive"]
    volumes:
      - ./test-results/comprehensive:/app/test-results
    depends_on:
      - frontend
    networks:
      - test-network

  test-mobile-core:
    build:
      context: ../../
      dockerfile: ci/docker/Dockerfile.test-runner
    environment:
      - BACKEND_URL=http://backend:9876
      - FRONTEND_URL=http://frontend:18473
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/econ_graph_test
    command: ["npm", "run", "test:e2e:mobile:core"]
    volumes:
      - ./test-results/mobile-core:/app/test-results
    depends_on:
      - frontend
    networks:
      - test-network

  test-mobile-analysis:
    build:
      context: ../../
      dockerfile: ci/docker/Dockerfile.test-runner
    environment:
      - BACKEND_URL=http://backend:9876
      - FRONTEND_URL=http://frontend:18473
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/econ_graph_test
    command: ["npm", "run", "test:e2e:mobile:analysis"]
    volumes:
      - ./test-results/mobile-analysis:/app/test-results
    depends_on:
      - frontend
    networks:
      - test-network

  test-mobile-comprehensive:
    build:
      context: ../../
      dockerfile: ci/docker/Dockerfile.test-runner
    environment:
      - BACKEND_URL=http://backend:9876
      - FRONTEND_URL=http://frontend:18473
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/econ_graph_test
    command: ["npm", "run", "test:e2e:mobile:comprehensive"]
    volumes:
      - ./test-results/mobile-comprehensive:/app/test-results
    depends_on:
      - frontend
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
