apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-data-service
  labels:
    app: financial-data-service
    component: financial-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: financial-data-service
  template:
    metadata:
      labels:
        app: financial-data-service
        component: financial-data
    spec:
      containers:
      - name: financial-data-service
        image: econ-graph-financial-data:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: RUST_LOG
          value: "info"
        - name: RUST_BACKTRACE
          value: "1"
        - name: DATA_DIR
          value: "/app/data"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: financial-data-pvc
