apiVersion: v1
kind: Service
metadata:
  name: financial-data-service
  labels:
    app: financial-data-service
spec:
  selector:
    app: financial-data-service
  ports:
  - port: 3001
    targetPort: 3001
    name: http
  type: ClusterIP
