apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart-api-service
  namespace: econ-graph
  labels:
    app: chart-api-service
    component: chart-api
    tier: internal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chart-api-service
  template:
    metadata:
      labels:
        app: chart-api-service
        component: chart-api
        tier: internal
    spec:
      containers:
      - name: chart-api-service
        image: econ-graph-chart-api:v1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
