apiVersion: v1
kind: Service
metadata:
  name: chart-api-service
  namespace: econ-graph
  labels:
    app: chart-api-service
    component: chart-api
    tier: internal
  annotations:
    # Internal service - not exposed externally
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP  # Internal service only
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: chart-api-service
  sessionAffinity: None
