apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: econ-graph-frontend-ingress
  namespace: econ-graph
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://econgraph.com,https://admin.econgraph.com,http://localhost:3000,http://localhost:3001"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "5"
spec:
  ingressClassName: nginx
  rules:
  - host: frontend.econ-graph.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: econ-graph-frontend-service
            port:
              number: 3000
