apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-service
  namespace: econ-graph
  labels:
    app: keycloak-postgresql
    component: database
    tier: infrastructure
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: keycloak-postgresql
