apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-service
  namespace: econ-graph
  labels:
    app: keycloak-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: keycloak-postgres
