apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: econ-graph
type: Opaque
data:
  # Base64 encoded values - in production, use proper secret management
  # Default passwords (change in production!)
  admin-password: YWRtaW4xMjM=  # admin123
  db-password: a2V5Y2xvYWsxMjM=  # keycloak123
  # Client secrets for EconGraph applications
  econ-graph-frontend-secret: ZnJvbnRlbmQtY2xpZW50LXNlY3JldA==  # frontend-client-secret
  econ-graph-backend-secret: YmFja2VuZC1jbGllbnQtc2VjcmV0  # backend-client-secret
