apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: econ-graph
  labels:
    app: keycloak
    component: auth
    tier: infrastructure
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: management
    port: 9990
    targetPort: 9990
    protocol: TCP
  selector:
    app: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  namespace: econ-graph
  labels:
    app: keycloak
    component: auth
    tier: infrastructure
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: management
    port: 9990
    targetPort: 9990
    protocol: TCP
  selector:
    app: keycloak
