# PostgreSQL deployment for local development
# Note: This assumes you have PostgreSQL running on the host
# For production, use a managed database service

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: econ-graph
  labels:
    app: postgres
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres

---
# Alternative: If you want to run PostgreSQL in the cluster
# Uncomment the following resources:

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgres
#   namespace: econ-graph
#   labels:
#     app: postgres
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#       - name: postgres
#         image: postgres:15-alpine
#         ports:
#         - containerPort: 5432
#         env:
#         - name: POSTGRES_DB
#           value: "econ_graph"
#         - name: POSTGRES_USER
#           value: "econ_user"
#         - name: POSTGRES_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: econ-graph-secrets
#               key: database-password
#         volumeMounts:
#         - name: postgres-storage
#           mountPath: /var/lib/postgresql/data
#       volumes:
#       - name: postgres-storage
#         emptyDir: {}
