# PostgreSQL initialization ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init
  namespace: econ-graph
data:
  init.sql: |
    -- Initialize database for EconGraph
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";
    CREATE EXTENSION IF NOT EXISTS "pg_trgm";

    -- Create user for the application
    CREATE USER econgraph WITH ENCRYPTED PASSWORD 'password';
    GRANT ALL PRIVILEGES ON DATABASE econ_graph TO econgraph;
    GRANT ALL ON SCHEMA public TO econgraph;
