apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: econ-graph
  labels:
    app: vault
    component: security
    tier: infrastructure
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8200
    targetPort: 8200
    protocol: TCP
  - name: https-internal
    port: 8201
    targetPort: 8201
    protocol: TCP
  selector:
    app: vault
---
apiVersion: v1
kind: Service
metadata:
  name: vault-headless
  namespace: econ-graph
  labels:
    app: vault
    component: security
    tier: infrastructure
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8200
    targetPort: 8200
    protocol: TCP
  - name: https-internal
    port: 8201
    targetPort: 8201
    protocol: TCP
  selector:
    app: vault
