name: E2E Tests (Unified)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      test_group:
        description: 'Test group to run'
        required: false
        default: 'core'
        type: choice
        options:
          - core
          - analysis
          - debug
          - comprehensive
          - mobile-core
          - mobile-analysis
          - mobile-comprehensive
          - all
      parallel:
        description: 'Run all test groups in parallel'
        required: false
        default: false
        type: boolean

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run E2E Tests
      run: |
        cd ci
        if [ "${{ github.event.inputs.parallel }}" = "true" ]; then
          ./scripts/run-tests-unified.sh --parallel
        elif [ "${{ github.event.inputs.test_group }}" = "all" ]; then
          ./scripts/run-tests-unified.sh --parallel
        else
          ./scripts/run-tests-unified.sh --group ${{ github.event.inputs.test_group || 'core' }}
        fi

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results
        path: ci/test-results/
        retention-days: 7
