import assert from 'node:assert/strict';
import { test } from 'node:test';
import { render, resolve } from '../merge.js';

const flag = (defaultVariant, kind, extra = {}) => ({
  state: 'ENABLED',
  variants: { on: true, off: false },
  defaultVariant,
  metadata: { kind },
  ...extra,
});

const release = {
  flags: {
    world_map: flag('off', 'build'),
    csv_download: flag('on', 'ops'),
    mcp: flag('off', 'build'),
    old: flag('on', 'ops', { state: 'DISABLED' }),
  },
};
const dev = { flags: { mcp: { state: 'ENABLED', variants: { on: true, off: false }, defaultVariant: 'on' } } };

test('release profile is the release file alone, sorted by key', () => {
  const { profile, flags } = resolve(release, dev, 'release');
  assert.equal(profile, 'release');
  assert.deepEqual(Object.keys(flags), ['csv_download', 'mcp', 'world_map']);
  assert.deepEqual(flags.mcp, { kind: 'build', value: false });
  assert.deepEqual(flags.csv_download, { kind: 'ops', value: true });
});

test('dev profile applies dev overrides and keeps the release kind', () => {
  const { flags } = resolve(release, dev, 'dev');
  assert.deepEqual(flags.mcp, { kind: 'build', value: true });
  assert.deepEqual(flags.world_map, { kind: 'build', value: false });
});

test('a DISABLED flag is left out', () => {
  assert.equal('old' in resolve(release, dev, 'release').flags, false);
});

test('an unknown profile throws', () => {
  assert.throws(() => resolve(release, dev, 'staging'), /unknown profile/);
});

test('render is stable JSON with a trailing newline and a generated header', () => {
  const text = render(resolve(release, dev, 'dev'));
  assert.ok(text.endsWith('}\n'));
  assert.match(JSON.parse(text).$comment, /Generated by scripts\/flags-merge/);
  assert.equal(text, render(resolve(release, dev, 'dev')));
});
