// Resolves config/flags into one file per build profile. The frontend and
// backend Docker builds use ./frontend and ./backend as their context and
// cannot see config/flags, so they read these generated files instead, and
// neither re-implements the merge.

export const PROFILES = ['release', 'dev'];
export const TARGETS = ['frontend/flags', 'backend/flags'];

const HEADER = 'Generated by scripts/flags-merge from config/flags. Do not edit; run node scripts/flags-merge.';

// release, dev: the parsed flag files. A dev entry replaces the release entry
// with the same key whole (flagd's rule for several sources), so the release
// profile is the release file alone and the dev profile is dev over release.
export function resolve(release, dev, profile) {
  if (!PROFILES.includes(profile)) throw new Error(`unknown profile "${profile}"`);
  const flags = { ...release.flags, ...(profile === 'dev' ? dev.flags : {}) };
  const resolved = {};
  for (const name of Object.keys(release.flags).sort()) {
    const flag = flags[name];
    // flagd treats a DISABLED flag as absent, so callers fall back to their code default
    if (flag.state !== 'ENABLED') continue;
    resolved[name] = { kind: release.flags[name].metadata.kind, value: flag.variants[flag.defaultVariant] };
  }
  return { $comment: HEADER, profile, flags: resolved };
}

export function render(resolved) {
  return `${JSON.stringify(resolved, null, 2)}\n`;
}
