name: Instant PATH Test

on:
  workflow_dispatch:

jobs:
  test-path:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - name: Install build tools
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential
        echo "cc installed: $(which cc)"

    - name: Test PATH expansion issue
      run: |
        echo "=== REPRODUCING THE ISSUE ==="
        echo "HOME: $HOME"
        echo "Original PATH: $PATH"
        echo "Setting PATH like in our CI:"
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "New PATH: $PATH"
        echo "Testing which cc:"
        which cc || echo "❌ cc not found - THIS IS THE ISSUE"
        echo "Testing cc command:"
        cc --version || echo "❌ cc command failed"
        echo "=== END TEST ==="
