name: Test YAML Environment Variables

on:
  workflow_dispatch:

jobs:
  test-yaml-env:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - name: Install build tools
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential
        echo "cc installed: $(which cc)"

    - name: Test YAML env PATH (old way)
      run: |
        echo "=== TESTING YAML ENV PATH (OLD WAY) ==="
        echo "Current PATH: $PATH"
        echo "Testing which cc:"
        which cc || echo "❌ cc not found"
        echo "Testing cc command:"
        cc --version || echo "❌ cc command failed"
        echo "=== END YAML ENV TEST ==="
      env:
        PATH: $HOME/.cargo/bin:$PATH

    - name: Test YAML env PATH (new way)
      run: |
        echo "=== TESTING YAML ENV PATH (NEW WAY) ==="
        echo "Current PATH: $PATH"
        echo "Testing which cc:"
        which cc || echo "❌ cc not found"
        echo "Testing cc command:"
        cc --version || echo "❌ cc command failed"
        echo "=== END YAML ENV TEST ==="
      env:
        PATH: ${{ runner.home }}/.cargo/bin:$PATH
