name: Test PATH Fix

# Disabled auto-triggering - this is a test workflow
# on:
  # Disabled auto-triggering - this is a test workflow
  # workflow_dispatch:
  # push:
  #   branches: [ test-path-fix ]

jobs:
  test-path-expansion:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install system build tools
      run: |
        echo "=== INSTALLING BUILD TOOLS ==="
        sudo apt-get update && sudo apt-get install -y build-essential
        echo "cc version: $(cc --version)"
        echo "gcc version: $(gcc --version)"
        echo "=== BUILD TOOLS INSTALLED ==="

    - name: Test PATH expansion (old way)
      run: |
        echo "=== TESTING OLD PATH SYNTAX ==="
        echo "HOME variable: $HOME"
        echo "PATH with \$HOME: $HOME/.cargo/bin:$PATH"
        echo "Testing which cc with old PATH:"
        export PATH="$HOME/.cargo/bin:$PATH"
        which cc || echo "cc not found with old PATH syntax"
        echo "=== END OLD PATH TEST ==="

    - name: Test PATH expansion (new way)
      run: |
        echo "=== TESTING NEW PATH SYNTAX ==="
        echo "runner.home: ${{ runner.home }}"
        echo "PATH with runner.home: ${{ runner.home }}/.cargo/bin:$PATH"
        echo "Testing which cc with new PATH:"
        export PATH="${{ runner.home }}/.cargo/bin:$PATH"
        which cc || echo "cc not found with new PATH syntax"
        echo "=== END NEW PATH TEST ==="

    - name: Test Rust compilation with old PATH
      run: |
        echo "=== TESTING RUST COMPILATION WITH OLD PATH ==="
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "Current PATH: $PATH"
        echo "Testing cargo --version:"
        cargo --version || echo "cargo not found"
        echo "Testing cc availability:"
        which cc || echo "cc not found"
        echo "=== END RUST COMPILATION TEST ==="

    - name: Test Rust compilation with new PATH
      run: |
        echo "=== TESTING RUST COMPILATION WITH NEW PATH ==="
        export PATH="${{ runner.home }}/.cargo/bin:$PATH"
        echo "Current PATH: $PATH"
        echo "Testing cargo --version:"
        cargo --version || echo "cargo not found"
        echo "Testing cc availability:"
        which cc || echo "cc not found"
        echo "=== END RUST COMPILATION TEST ==="
