name: Test Shell Expansion in GitHub Actions

# Disabled auto-triggering - this is a test workflow
# on:
#   workflow_dispatch:

env:
  # This should be expanded by GitHub Actions at workflow level
  WORKFLOW_LEVEL_VAR: "workflow-expanded"
  # This should be treated as literal by GitHub Actions, expanded by shell in job
  SHELL_EXPANSION_VAR: "$HOME/.cargo/bin"

jobs:
  test-shell-expansion:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Test GitHub Actions vs Shell expansion
      run: |
        echo "=== TESTING EXPANSION BEHAVIOR ==="
        echo "WORKFLOW_LEVEL_VAR: $WORKFLOW_LEVEL_VAR"
        echo "SHELL_EXPANSION_VAR: $SHELL_EXPANSION_VAR"
        echo "HOME variable: $HOME"
        echo "=== END EXPANSION TEST ==="
      env:
        # This should be expanded by shell during job execution
        JOB_LEVEL_SHELL_VAR: "$HOME/.cargo/bin"
        # This should be expanded by GitHub Actions before job execution
        JOB_LEVEL_WORKFLOW_VAR: "${{ env.WORKFLOW_LEVEL_VAR }}"

    - name: Test literal vs expanded behavior
      run: |
        echo "=== TESTING LITERAL VS EXPANDED ==="
        echo "JOB_LEVEL_SHELL_VAR (should expand to actual path): $JOB_LEVEL_SHELL_VAR"
        echo "JOB_LEVEL_WORKFLOW_VAR (should be pre-expanded): $JOB_LEVEL_WORKFLOW_VAR"
        echo "=== END LITERAL VS EXPANDED TEST ==="

    - name: Test actual shell expansion methods
      run: |
        echo "=== TESTING ACTUAL SHELL EXPANSION METHODS ==="
        echo "Method 1 - Direct shell expansion:"
        export EXPANDED_PATH="$HOME/.cargo/bin"
        echo "EXPANDED_PATH: $EXPANDED_PATH"

        echo "Method 2 - Using eval:"
        eval "export EVAL_PATH=$HOME/.cargo/bin"
        echo "EVAL_PATH: $EVAL_PATH"

        echo "Method 3 - Using printf:"
        export PRINTF_PATH=$(printf "%s" "$HOME/.cargo/bin")
        echo "PRINTF_PATH: $PRINTF_PATH"

        echo "=== END SHELL EXPANSION METHODS TEST ==="

    - name: Test key expansion patterns
      run: |
        echo "=== TESTING KEY EXPANSION PATTERNS ==="
        echo "1. Plain \$HOME: $PLAIN_HOME"
        echo "2. Escaped \\\$HOME: $ESCAPED_HOME"
        echo "3. Single quotes '\$HOME': $SINGLE_QUOTED_HOME"
        echo "4. Double quotes \"\$HOME\": $DOUBLE_QUOTED_HOME"
        echo "5. GitHub Actions \${{ runner.temp }}: $GITHUB_ACTIONS_HOME"
        echo "6. Curly braces \${HOME}: $CURLY_BRACES_HOME"
        echo "7. Command substitution \$(echo \$HOME): $COMMAND_SUB_HOME"
        echo "=== END KEY PATTERNS TEST ==="
      env:
        PLAIN_HOME: "$HOME/.cargo/bin"
        ESCAPED_HOME: "\\$HOME/.cargo/bin"
        SINGLE_QUOTED_HOME: '$HOME/.cargo/bin'
        DOUBLE_QUOTED_HOME: "$HOME/.cargo/bin"
        GITHUB_ACTIONS_HOME: "${{ runner.temp }}/.cargo/bin"
        CURLY_BRACES_HOME: "${HOME}/.cargo/bin"
        COMMAND_SUB_HOME: "$(echo $HOME)/.cargo/bin"
